### ISSUE TITLE
Cannot create database with alternate steps

### ISSUE THREAD

**Issue by theoddpolymath** [chriscauley/txrx.org#114]
**Environment**

- Linux 3.16.0-4-amd64
- Debian 3.16.36-1+deb8u2 (2016-10-19)
- Python in a virtualenv

**Cause**

- Follow steps in README
- Install required Python packages
- Create database; use alternate steps
`python manage.py syncdb`

**Effect**
_Error_
`Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management`

**Troubleshooting**

- Upgrade Django
`pip install --upgrade django
Collecting django
  Downloading Django-1.10.4-py2.py3-none-any.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 104kB/s 
Installing collected packages: django
Successfully installed django-1.10.4`
- Create database; use alternate steps
`python manage.py syncdb`
- _Error_
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.virtualenvs/txrxorg/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/user/.virtualenvs/txrxorg/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/home/user/.virtualenvs/txrxorg/local/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/user/.virtualenvs/txrxorg/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/user/.virtualenvs/txrxorg/local/lib/python2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/Projects/txrx.org/main/settings/__init__.py", line 116, in <module>
    from rest_framework_jwt.settings import DEFAULTS as JWT_AUTH
ImportError: No module named rest_framework_jwt.settings`
- Install, upgrade djangorestframework -> Package already installed, up-to-date; same error

**Comment by theoddpolymath** [comment]
- My fork fell 28 commits behind the master repo
- Merged
- Followed steps to reproduce the issue; issue still happens
