### ISSUE TITLE
syncdb step of install instructions issue

### ISSUE THREAD

**Issue by Davorak** [chriscauley/txrx.org#71]
With django 1.5.9 installed I get:

```
$ python manage.py syncdb
Setting file missing. We looked here: txrx/settings/local.py
ImportError: No module named django_comments.signals
```

With django 1.6.6 installed I get:

```
$ python manage.py syncdb
Setting file missing. We looked here: txrx/settings/local.py
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/pjw/code/project/txrxWeb/txrx.org/nixShellVirtualEnv/src/django-mptt-comments/mptt_comments/__init__.py", line 3, in <module>
    from django_comments.signals import comment_was_posted
ImportError: No module named django_comments.signals
```

**Comment by Davorak** [comment]
Installing:

django-contrib-comments                                                                                                                                         
south 1.0.2                                                                                                                                                      
django-suit  0.2.13                                                                                                                                               
django-markup 0.4                                                                                                                           
markup 0.2    


got me to:

```
$ python manage.py syncdb
Setting file missing. We looked here: txrx/settings/local.py
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/pjw/code/project/txrxWeb/txrx.org/nixShellVirtualEnv/lib/python2.7/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/nix/store/k91xq0ifx3nhzmrqccgcfhiikna5pm8f-python2.7-Django-1.6.6/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 25, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError django.contrib.markup: No module named markup
```

Which might be related to:
http://stackoverflow.com/questions/20055603/how-can-i-satisfy-a-django-contrib-markup-templatetags-markup-import-restructure

**Comment by Davorak** [comment]
Ok as suggested over cat I tried django 1.4 and that seems to be working better.

I was able to install:
django-contrib-comments 1.6.1                                                    
south 1.0.2                                                                      
django-suit  0.2.13                                                              
django-markdown-deux 1.0.5                                                       
django-bootstrap-form 3.2

before I got the error:

```
$ python manage.py syncdb
Setting file missing. We looked here: txrx/settings/local.py
Setting file missing. We looked here: txrx/settings/local.py
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/nix/store/s6clh55n9jwqqpxjbj8yz66yd177580w-python2.7-Django-1.4.14/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/nix/store/s6clh55n9jwqqpxjbj8yz66yd177580w-python2.7-Django-1.4.14/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/nix/store/s6clh55n9jwqqpxjbj8yz66yd177580w-python2.7-Django-1.4.14/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/nix/store/s6clh55n9jwqqpxjbj8yz66yd177580w-python2.7-Django-1.4.14/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/nix/store/s6clh55n9jwqqpxjbj8yz66yd177580w-python2.7-Django-1.4.14/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/nix/store/s6clh55n9jwqqpxjbj8yz66yd177580w-python2.7-Django-1.4.14/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/nix/store/s6clh55n9jwqqpxjbj8yz66yd177580w-python2.7-Django-1.4.14/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/nix/store/s6clh55n9jwqqpxjbj8yz66yd177580w-python2.7-Django-1.4.14/lib/python2.7/site-packages/django/db/models/loading.py", line 67, in _populate
    self.load_app(app_name)
  File "/nix/store/s6clh55n9jwqqpxjbj8yz66yd177580w-python2.7-Django-1.4.14/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/nix/store/s6clh55n9jwqqpxjbj8yz66yd177580w-python2.7-Django-1.4.14/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/pjw/code/project/txrxWeb/txrx.org/nixShellVirtualEnv14/src/django-registration/registration/models.py", line 7, in <module>
    from django.contrib.auth import get_user_model
ImportError: cannot import name get_user_model
```

**Comment by Davorak** [comment]
Here is the nix-shell script I am working with:
https://github.com/Davorak/experiments/blob/master/txrx.org/shell.nix
